# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            'Saline Rowing'
tagline:          'We Row, Do You?'
description:      'Saline Rowing Club, Saline, Michigan'
url:              http://salinerowing.org
baseurl:          '/'
paginate:         10

author:
  name:           'Mike Ward'
  email:          'mike@wardfam.org'
  url:            'https://twitter.com/mikeward_aa'

version:          '1.0.0'

github:
  repo:           'https://github.com/salinecrew'

sass:
    style:        ':compressed'

gems:
  - jekyll-seo-tag